version: '3.8'

services:
  frontend:
    image: paoluhm65/app-filmes-frontend:latest
    ports:
      - "4200:80"
    container_name: appfilmes_frontend
    restart: always
    depends_on:
      - backend

  backend:
    image: paoluhm65/app-filmes-backend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data
    container_name: appfilmes_backend
    restart: always
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 15 # Verifica por novas imagens a cada 60 segundos
    restart: always
    container_name: watchtower
